services:
  kata-db:
    container_name: kata-db
    image: postgres:16.3
    command: ["postgres", "-c", "log_statement=all"]
    env_file:
      - .env.local
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: no
